packages:
  - .

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  '@modelcontextprotocol/sdk@>=1.10.0 <=1.25.3': '>=1.26.0'
  hono@<4.11.7: '>=4.11.7'
  next@>=15.6.0-canary.0 <16.1.5: '>=16.1.5'
  next@>=16.0.0-beta.0 <16.1.5: '>=16.1.5'
  next@>=16.1.0-canary.0 <16.1.5: '>=16.1.5'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
